### ISSUE TITLE
Previewed page opens fully and changes tab history

### ISSUE THREAD

**Issue by Illiou** [degecko/prevue#5]
Some pages open just very briefly in the sidebar and then open normally in full in the current tab. I'm assuming it has something to do with iframe security shenanigans.
Example for testing (any of the links leading back to stackexchange/overflow): https://stackoverflow.blog/2020/11/09/modern-ide-vs-vim-emacs/

The first problem with it is simply that I don't want that to happen - if the link can't be preview for some reason I'd rather not have it open automatically (maybe a setting for that would work).

But second, and more importantly, if the link is opened in full like that, it replaces the last site in the current tab history, which means if you want to go back by pressing the back button, it's not possible anymore and you don't even know which site you were on previously!
That is rather a dealbreaker for me, so I hope you get around to fixing this!

Thank you

(Firefox 105.0.1 on Windows 10)

**Comment by degecko** [comment]
Unfortunately, this is hard to circumvent for all websites, because I don't think it's a standard way that they do that.

I've noticed this on Reddit as well. It works fine when opening external URLs, but when you open another Reddit link, it will switch the entire page to that link. They probably have some way to prevent framing their own site for whatever reason.

It's indeed annoying, I will try to figure out a way to at least prevent the redirect to the previewed URL, but I can't promise anything.

Thanks for taking the time to review!

**Comment by Illiou** [comment]
Ah true, that reminds me of an article or video I recently saw, which described the various ways early websites found to break out of iframes. Can't seem to find it right now though.
Maybe restoring the original URL after noticing a breakout would work. And if somehow it turns out to be easier, I'd be happy with the original URL remaining/being put back into the tab history so that pressing back works (although I guess it'd need to be careful not to break more in the process, tab history always seemed fragile to me). Thanks for any effort in any case!
